cursor = "/ui/cursor_normal.png"
bottom_left_corner = "/ui/cursor_bottom_left_corner.png"
bottom_right_corner = "/ui/cursor_bottom_right_corner.png"
bottom_side = "/ui/cursor_bottom_side.png"
left_side = "/ui/cursor_left_side.png"
right_side = "/ui/cursor_right_side.png"
window_max = "/ui/cursor_window_max.png"
window_max_unfocused = "/ui/cursor_window_max_unfocused.png"
window_close = "/ui/cursor_window_close.png"
window_close_unfocused = "/ui/cursor_window_close_unfocused.png"